### ISSUE TITLE
Enemies blow themselves up some times

### ISSUE THREAD

**Issue by ZavixDragon** [EnigmaDragons/LDJam44#161]

**Comment by gordykeene** [comment]
You are in good company!

> In 1956, the Grumman aircraft corporation was testing its new fighter, the F-11 Tiger, off the coast of New York state. The pilot fired a long burst from its guns and moments later suffered mysterious, catastrophic damage that caved in the windshield and mortally wounded the engine. What happened? The pilot had shot himself down.

https://www.popularmechanics.com/military/aviation/a27967/the-fighter-plane-that-shot-itself-down/
