### ISSUE TITLE
Unable to spend all Life Force

### ISSUE THREAD

**Issue by gordykeene** [EnigmaDragons/LDJam44#82]
Unable to purchase a final unit, even through the Life Force appear to be available.

![2019-04-28_10h26_25.png](https://zube.io/files/enigmadragons/95b7a2dd7e5ff2007dd150a58d9c0da2-2019-04-28_10h26_25.png)

**Comment by SilasReinagel** [comment]
This is working as intended.

What needs to happen is more UI clarity about the fact that you are spending your Max Lifeforce for the next delivery.

**Comment by gordykeene** [comment]
Oh, after updating it with image with the latest build, I read the "as intended" comment. Okay, never mind!

**Comment by SilasReinagel** [comment]
Tutorial + HP Visualization will solve this.
